version: 2
jobs:
    build:
        docker:
            - image: node
        steps:
            - checkout
            - restore_cache:
                key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - run: npm i
            - save_cache:
                key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - node_modules
